Repository dbt-labs/dbt-codegen, pull requests merged in 2024-12, with the labels that each got.

#227 Update changelog for 0.13.0 release
  CHANGELOG.md
Labels: size:M

#230 Temporarily remove CI test for case-sensitive identifiers when generating sources
  integration_tests/dbt_project.yml
  integration_tests/seeds/data__Case_Sensitive.csv
  integration_tests/tests/test_generate_source_case_sensitive.sql
Labels: size:M

#234 Upgrade from Postgres 9 to 17
  .circleci/config.yml
  docker-compose.yml
Labels: size:XS

#235 Trigger CI off `pull_request_target` so workflow runs in the context of the base branch
  .github/workflows/ci.yml
Labels: size:XS

#236 Bigquery repeated data type
  integration_tests/models/model_repeated.sql
  integration_tests/tests/test_generate_model_repeated_yaml.sql
  integration_tests/tests/test_helper_get_models.sql
  macros/vendored/dbt_core/format_column.sql
Labels: size:M

#239 Remove "I have added an entry to CHANGELOG.md" from the PR template
  .github/pull_request_template.md
Labels: size:XS

#240 Contributors shouldn't edit the `CHANGELOG.md` directly anymore
  CONTRIBUTING.md
Labels: size:XS

#243 Remove the PR checklist items related to the type of change
  .github/pull_request_template.md
Labels: size:XS

#244 Align the PR description with dbt-core, dbt-adapters, etc.
  .github/pull_request_template.md
Labels: size:S

#246 Align the pull request template with `dbt-utils`
  .github/pull_request_template.md
Labels: size:XS
