Repository dbt-labs/dbt-codegen, pull requests merged in 2024-11, with the labels that each got.

#198 add snowflake
  .github/workflows/ci.yml
  .gitignore
  integration_tests/profiles.yml
  supported_adapters.env
  tox.ini
Labels: size:M

#199 Fix quoted identifiers in the `generate_base_model` macro for BigQuery
  integration_tests/macros/operations/create_source_table.sql
  integration_tests/tests/test_generate_base_models_all_args.sql
  integration_tests/tests/test_generate_base_models_case_sensitive.sql
  macros/generate_base_model.sql
Labels: size:S

#208 Try removing Redshift-specific logic for toggling case-sensitive identifiers
  integration_tests/macros/operations/create_source_table.sql
Labels: size:S

#214 Use the `cimg/postgres` Docker image created by CircleCI with continu…
  .circleci/config.yml
Labels: size:XS

#215 Independent workflow job for dbt-postgres
  .circleci/config.yml
Labels: size:L

#216 Simplify environment variables for BigQuery in CircleCI
  .circleci/config.yml
Labels: size:XS

#220 Stop installing prereleases from PyPI in favor of stable releases only
  .circleci/config.yml
  Makefile
  integration_tests/README.md
Labels: size:S

#222 Upgrade to Python 3.11 in CircleCI
  .circleci/config.yml
Labels: size:XS

#224 Use dynamic schema names rather than hardcoded ones
  integration_tests/macros/operations/create_source_table.sql
  integration_tests/models/model_without_import_ctes.sql
  integration_tests/models/source.yml
  integration_tests/tests/test_generate_model_import_ctes.sql
  integration_tests/tests/test_generate_model_import_ctes_leading.sql
Labels: size:S

#203 Add support for bigquery testing in GitHub CI via tox
  .github/workflows/ci.yml
  integration_tests/profiles.yml
  supported_adapters.env
  tox.ini
Labels: size:M
